# Name of your workflow.
name: flutter drive
run-name: Integration Test
on:
  pull_request:
    branches:
      - main
# A workflow run is made up of one or more jobs.
jobs:
  # id of job, a string that is unique to the "jobs" node above.
  drive:
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    strategy:
      # A set of different configurations of the virtual  
      # environment.
      matrix:
        device:
        - "iPhone 13"
      # When set to true, GitHub cancels all in-progress jobs if any        
      # matrix job fails.
      fail-fast: false
    # The type of machine to run the job on.
    runs-on: macOS-latest
    # Contains a sequence of tasks.
    steps:
    # A name for your step to display on GitHub.
    - name: "Delete Unavailable Sims"
      run: "xcrun simctl delete unavailable"

    - name: "List all simulators"
      run: "xcrun simctl list devices"

    - name: "Start Simulator"
      run: |
        UDID=$(xcrun simctl list devices | awk '/iPhone 13/ {gsub(/[()]/,""); a=$3} END{ print a;}')
        echo Booting up device... 
        echo Device ID: $UDID 
        xcrun simctl boot $UDID
    # The branch or tag ref that triggered the workflow will be 
    # checked out.
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'dev' or 'beta'
    - name: "Run Flutter Tests"
      run: "flutter test integration_test"